### ISSUE TITLE
포스팅 잘보았습니다 :)

### ISSUE THREAD

**Issue by kyechan99** [NewWisdom/NewWisdom#1]
[velog](https://velog.io/@new_wisdom/git-%EA%B0%84%EC%A3%BD%EA%B0%84%EC%82%B4-git-profile-%EA%BE%B8%EB%AF%B8%EA%B8%B0)에 capsule-render 사용한 포스팅 잘 보았습니다 :)
정말 감사드리고 기쁩니다. ㅎㅎㅎ

별 다른건 아니구 `header, footer 컬러 조합이 새로고침마다 너무 언발란스~~` 라고 말씀해 주셔서요.

사실 color 기능에 `timeAuto` 와 `timeGradient` 기능이 있습니다.
(1분 간격으로 색이 바뀌는 형태인지라)새로 고침할때마다 색이 바뀌기는 힘들지만 header, footer 같이 동적 색 변환을 사용할 수는 있습니다.

다시 한번 감사드립니다  :smile:

**Comment by NewWisdom** [comment]
안녕하세요:)
깃 프로필 꾸밀 수 있는 좋은 오픈 소스 제공해주셔서 저야말로 너무 감사드려요!

왜때문인지 timeAuto를 써도 header와 footer가 가끔 다른 조합이 나와서 저렇게 작성했었네요😅

누추한 제 포스팅 봐주셔서 감사하고 좋은 소스 저도 너무 감사드립니다😄

2020년 11월 7일 (토) 오후 12:24, Ye-Chan Kang <notifications@github.com>님이 작성:

**Comment by kyechan99** [comment]
앗 이미 알고계셨군요..
여러 테스트에선 문제가 없어서 추가했지만 그럼에도 문제가 있었네요.
덕분에 버그하나 알아가네요 :) 감사합니다
